CREATE OR REPLACE STREAM "DADOS_SAIDA"(
    HORA VARCHAR(4), 
    DC_NOME VARCHAR(16), 
    CD_ESTACAO VARCHAR(4), 
    VL_LATITUDE DOUBLE, 
    VL_LONGITUDE DOUBLE,
    TEM_MAX REAL,
    PRE_MIN REAL,
    TEM_MIN REAL,
    VEN_VEL REAL,
    CHUVA REAL
);

CREATE OR REPLACE PUMP "STREAM_PUMP" AS INSERT INTO "DADOS_SAIDA"
    SELECT STREAM HORA, DC_NOME, CD_ESTACAO, VL_LATITUDE, VL_LONGITUDE, TEM_MAX, PRE_MIN, TEM_MIN, VEN_VEL, CHUVA FROM(
        SELECT STREAM HORA, DC_NOME, CD_ESTACAO, VL_LATITUDE, VL_LONGITUDE, MAX(TEM_MAX) TEM_MAX, MIN(PRE_MIN) PRE_MIN, MIN(TEM_MIN) TEM_MIN, AVG(VEN_VEL) VEN_VEL, CHUVA
            FROM "SOURCE_SQL_STREAM_001"
            GROUP BY HORA, DC_NOME, CD_ESTACAO, VL_LATITUDE, VL_LONGITUDE, CHUVA, 
            STEP("SOURCE_SQL_STREAM_001".ROWTIME BY INTERVAL '1' MINUTE)
        );
